# Generated by Django 4.1.7 on 2023-04-03 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_sighting_latitude_alter_sighting_longitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sighting',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=11),
        ),
        migrations.AlterField(
            model_name='sighting',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=11),
        ),
    ]
